image: continuumio/miniconda3:latest

cache:
  paths:
    - envs

before_script:
  # - conda update conda  # Not strictly needed
  - conda install -qy anaconda-project
  - anaconda-project prepare
  
test:
  script:
    - anaconda-project run test
  artifacts:
    reports:
      cobertura: _htmlcov/coverage.xml
  coverage: '/Total coverage: (\d+\..*\%)$/'

test-assignment-0:
  script:
    - anaconda-project run test -k test_official_assignment_0 --no-cov

test-assignment-1:
  script:
    - anaconda-project run test -k test_official_assignment_1 --no-cov
    
