image: continuumio/miniconda3:latest

cache:
  paths:
    - envs

before_script:
  # - conda update conda  # Not strictly needed
  - conda install -qy anaconda-project
  - anaconda-project prepare
  
test:
  script:
    - anaconda-project run test
